src/flatpickr.js

So you can run a custom function when a date is selected

Added onClickEvent option

---

src/flatpickr.js

These to functions make it possible to easily jump to a specific date in the calendar or to set a new date (with the optional choice of triggering a change event).

Add public jumpToDate & setDate functions

---

src/flatpickr.l10n.sq.js

Here is the Albanian localization.

Albanian locals for flatpickr

---

src/flatpickr.l10n.tr.js

Here is the Turkish localization.

Add Turkish localization

---

src/flatpickr.js
src/flatpickr.l10n.es.js
src/flatpickr.l10n.no.js

Ordinal date suffix

---

src/style/flatpickr_base.styl

noticed a missing "." on a class selector and fixed it.

fixed a broken class selector

---

src/flatpickr.l10n.fr.js

Remove the letter y in the month May.

Fix month May

---

src/flatpickr.l10n.fi.js

Added finnish translation

---

src/flatpickr.l10n.es.js

In Spain Monday is the first day of week

Configure Monday as first day of week

---

src/flatpickr.l10n.ko.js

Added Republic of Korea localization (weekdays, months)

Added Republic of Korea localization

---

src/flatpickr.js

Now you can translate the title for the input year like that:
``` javascript
flatpickr.init.prototype.l10n.scrollTitle = 'Puede utilizar la ruleta del ratón';
```

Availability for change the title in input year

---

README.md

Concerning https://github.com/chmln/flatpickr/issues/126

Adding angular-addon link to readme

---

index.html

Just a couple minor doc corrections.

Doc corrections

---

index.html

Round 1
Feel free to reject any of the changes. Wasn't sure on some bits so I just guessed.

Docs update

---

index.html

Escaping all non-format chars in example

---

src/flatpickr.l10n.id.js

Hi,
I'm adding Indonesian translation. Thanks for the great package. :)

add Indonesian translation

---

src/flatpickr.l10n.my.js

Here is the malaysian localization for flatpickr.
Thanks

Malaysian localization

---

src/flatpickr.l10n.sv.js

Hey,
Added swedish localization to the project.

Add swedish l11n

---

assets/localizr.js
src/flatpickr.l10n.cat.js

Added support for the Catalan language.

Locale catalan

---

assets/js/localizr.js
src/flatpickr.l10n.ro.js

This adds the Romanian localisation options.

Add Romanian locale

---

package.json

The extra comma causes the JSON to be malformed, so just removing it.

Removed extra comma

---

src/l10n/cy.js

I don't speak Welsh myself, but I've done some research... 😅

Add Welsh localization

---

src/l10n/de.js

title pretty much sums it up :)

added rangeSeparator to german locals

---

dist/l10n/fr.js

Add the french translation for the rangeSeparator in the i10n files.

Add rangeSeparator translation

---

package.json

Enables support for npm-sass and more.

Add styles property to package.json

---

README.md
package.json

Now your open collective backers and sponsors can to appear directly on your README. 
see how it'll look [here](https://github.com/apex/apex#backers)
[More info](https://github.com/opencollective/opencollective/wiki/Github-banner)
Also add badges on top and [open collective post-install](https://github.com/OpenCollective/opencollective-postinstall)

added open collective

---

src/flatpickr.js

If  triggerChange in setDate is false - and date value is empty - "Change" event triggers whatever.

Fixed bug with setDate and triggerChange = false

---

src/plugins/confirmDate/confirmDate.js

dont append confirmDate to native inputs

---

src/l10n/sl.js

Add slovenian locale

---

src/l10n/sk.js

Created l10n/sk.js

---

src/l10n/eo.js

Add Esperanto locale

---

src/l10n/nl.js

Adds missing translations (weekAbbreviation, rangeSeparator, scrollTitle, toggleTitle)

Update dutch translations

---

src/l10n/no.js

Noticed that some translations was missing. Added them.

Added some missing translations in no.js

---

src/flatpickr.js
test/flatpickr.spec.js

Use separate formats for separate locales.

---

dist/l10n/index.js
src/l10n/index.js

A way to easy dynamic load locale, like:
`import * as flatPickrL10n from 'flatpickr/dist/l10n'`
And when you set option of new Flatpickr:
`{locale: flatPickrL10n[currentLang] }`
With currentLang the variable containing the lang key (for example 'fr')

Add index for l10n

---

content/options.md

It's mentioned in the text so it would be nice to link this for stupid people like me who don't know where to find "that table" :P

Update options.md to link to date-format options

---

src/l10n/da.js

Range separator should be ` til ` instead of `to`.
Also first day of week should be 1 (monday/mandag)

da.js - Set range separtor & first day of week

---

content/options.md

links to:
- event/hooks
- examples

Update options.md links

---

src/index.ts

if use ===, it will not work as I wish, case when i click the clear button, the triggerChangeEvent will be a Event Object

fix(index.ts#1204): remove === just check triggerChangeEvent

---

README.md

Update vue.js component link

---

src/l10n/tr.ts

Update turkish language

---

src/index.ts

This is a proposed fix for #910 - the issue ticket is updated with a description of what's causing the issue and the potential fix.

Issue #910

---

src/__tests__/index.spec.ts
src/index.ts

Updated KeyboardEvents functionality to use 'keyCode' instead of 'key'; Resolves #1156

 Resolves #1156 

---

src/plugins/weekSelect/weekSelect.ts

Someone just need to change the dateFormat

Posibility to change date format in WeekPicker plugin

---

src/index.ts

PR for issue #1228 
https://jsfiddle.net/kuythe08/

fix issue 1228

---

src/l10n/at.ts

In comparison to the German locale, only January differs.

Created locale for Austria

---

src/index.ts

Adds aria-current="date" on the current day for better accessibility. https://www.w3.org/TR/wai-aria-1.1/#aria-current

Add aria-current date

---

src/l10n/pl.ts

I've added some missing translations for polish

feat(translations): add missing polish translations

---

src/l10n/es.ts

Update spanish language

---

src/index.ts
src/utils/polyfills.ts

Fixes: forced reflow

---

emitDeclarations.sh

Minor fix to ease developers using mac os.

Use local tsc and support osx cp command

---

src/l10n/index.ts
src/l10n/km.ts
src/types/locale.ts

Provide additional translate file to Khmer locale (km).

Add Khmer Locale

---

src/l10n/hu.ts

update hungarian language

---

README.md

+ Change CircleCI badge style to match others

Add Svelte component

---

src/index.ts
src/utils/dom.ts

Fix event target in shadow dom

---

src/index.ts

What's changed
Triggering updateTime on close for a specific workflow
How to test:
1. Set up using param enableTime:true and an onClose event
2. Select a date
3. Change the time by typing in the number of hours or minutes (not using cursors)
4. Close flatpickr by clicking off
Time should change in the onClose event. I've also tested with just calendar and without calendar.
Notes:
Relates to https://github.com/flatpickr/flatpickr/issues/1581

Update time on close

---

src/index.ts

Fixes https://github.com/flatpickr/flatpickr/issues/1186

Fixes IE11 bug in close event

---

src/l10n/he.ts

- Fixed Saturday to correct shorthand.
- Added translation to "rangeSeparator".

Hebrew translations

---

src/index.ts

Populate time if unset in inline mode

---

src/style/flatpickr.styl
src/utils/dom.ts

Use input type number in supported browsers

---

src/index.ts

set() - remove jumpToDate()

---

src/index.ts

Handle enter keypress on time inputs

---

src/index.ts
src/style/flatpickr.styl

Fixes https://github.com/flatpickr/flatpickr/issues/1679

Fix num input (bug #1679)

---

src/__tests__/index.spec.ts
src/index.ts

Disable updateTime() on lost focus

---

src/index.ts

Disable style injection if not supported

---

src/__tests__/index.spec.ts
src/index.ts
src/types/instance.ts

Also adds `self.pluginElements` that can allow custom plugins to be focused on.
resolves #1421

Time picker focus out

---

src/index.ts

Fix startRange Styling

---

src/__tests__/index.spec.ts
src/index.ts
src/types/instance.ts

Fixes #1746 - no events triggered by jumpToDate

---

src/index.ts

Fix for https://github.com/flatpickr/flatpickr/issues/1756

fix for enter keypress in time inputs causing form submit #1756

---

build.ts
config/rollup.ts
src/index.ts

Some of these are recent changes made by me.
Maybe we should ask commiters to npm run fmt before commit to keep thing tidy.

npm run fmt (prettier)

---

src/l10n/bs.ts
src/l10n/index.ts
src/types/locale.ts

Added Bosnian (bs) translation which is similar to Croatian and Serbian with slight but noticeable differences.

Added Bosnian locale

---

src/style/flatpickr.styl

float left overrides display inline-block

Redundant Style

---

.eslintrc.js
src/plugins/rangePlugin.ts

Do we need this variable?
If not I will remove in a further commit.

Fix @typescript-eslint/no-unused-vars

---

index.template.html

- monthDropDown now lives in main library

Fix index template

---

src/plugins/rangePlugin.ts

Let's you use "wrap" with rangePlugin second input.

Add custom elements support to the rangePlugin

---

src/l10n/ga.ts

Please merge irish locale into repo! Tnx

Added irish locale

---

src/index.ts

Fixes the keyboard input being sneakily stolen from the year input by the time input

#1724 Fixed key up/down inside year num field

---

src/index.ts

#1688 Fixed let/right keys not working with appendTo

---

src/l10n/ga.ts
src/plugins/rangePlugin.ts

Formatting

---

src/index.ts

Fixes #1828
Essentially just making extra sure that everything is as expected.

Fix browser detection not detecting browser envs entirely correctly

---

src/index.ts
src/l10n/default.ts
src/types/locale.ts

Fixes #1825 by adding aria labels to the hour and minute inputs

#1825 Added aria labels to hour and minute inputs

---

README.md
src/l10n/index.ts
src/l10n/ka.ts
src/types/locale.ts

This PR adds Georgian (ka) localization

Add Georgian (ka) locale

---

src/index.ts

Fix #1805: right position calculation

---

src/index.ts

Fix for issue https://github.com/flatpickr/flatpickr/issues/1754

Fix Firefox not automatically updating time

---

src/types/options.ts

Hi, this is a really minor change but looking other options it was the only one without an explanation comment.
If you think is not useful feel free to reject.

Added comment to explain showMonths option

---

src/index.ts

days calculation is wrong on leap years 
https://github.com/flatpickr/flatpickr/issues/1963

Fix getDaysInMonth (leap years) https://github.com/flatpickr/flatpickr/issues/1963

---

src/index.ts

Fixes Fix: #1904. Attempt to access allowed style sheet and create one if none exist

Fix: #1904 Attempt to access allowed style sheet and create one if none exist

---

src/__tests__/index.spec.ts
src/index.ts
src/plugins/momentPlugin.ts
src/types/options.ts

Attempting to fix https://github.com/flatpickr/flatpickr/issues/2109 (which is a duplicate of https://github.com/flatpickr/flatpickr/issues/1551)
Proposed fix comes from @aximili (https://github.com/flatpickr/flatpickr/issues/1551#issuecomment-491677052).

Update date onBlur when allowInput is true

---

src/index.ts

It was imposible to clear value when time was enabled.

possibility to clear value when time enabled

---

package.json
src/plugins/monthSelect/index.ts

This PR fixes https://github.com/flatpickr/flatpickr/issues/2045.

Add support for ESM imports

---

package-lock.json
src/l10n/vn.ts

Hi bro,  
I'm from Vietnam, I edited longhand of filed month, I hope you accept my pull request. 
Thanks you very much

edit longhand vietnamese

---

src/plugins/rangePlugin.ts

Hi. I have issue when using RangePlugin with option "clickOpens: false".
I fix it in this commit.

Fix clickOpens option in RangePlugin

---

src/l10n/ja.ts

add japanese expression labels like as default.ts.

add l10n japanese expression

---

__tests__/src/index.spec.ts
src/index.ts
src/types/options.ts

Explanation: https://github.com/flatpickr/flatpickr/issues/2285#issuecomment-702698537
Closes: #2285

fix: enable option not working if array is blank

---

src/l10n/ko.ts

🌐[ko] Add missing am/pm translation

---

build.ts
src/plugins/scrollPlugin.ts
src/utils/index.ts
tsconfig.esm.json
tsconfig.json

Compile all ES6+ syntax to ES5

---

src/l10n/index.ts
src/l10n/nn.ts
src/types/locale.ts

Long time listener, first-time caller
This adds in the Norwegian Nynorsk sublocale `nn` with the help of @marijohannessen
Let me know if there's anything else needed on our end. Thanks for the great library!

feat: add norwegian nynorsk

---

src/l10n/gr.ts

Adjusts month abbreviation and adds aria-labels for the Greek translation (i10n)

Adjusts month abbreviation and adds aria-labels for the Greek translation (i10n)

---

src/plugins/scrollPlugin.ts

Check exsitance of years and month in scrollPlugin

---

src/index.ts

fix: `onClose` callback was returning wrong selected dates if user changed input before close.

---

src/l10n/cat.ts

Adding range separator to Catalan in cat.js

Add range separator to Catalan

---

README.md

- sorry I made a mistake when I made the original PR #2384, I forgot to update the url (it was linked to my lib not yours), this PR fixes it

fix: GitHub Actions badge fix invalid url typo

---

src/l10n/hy.ts
src/l10n/index.ts
src/types/locale.ts

add Armenian locale

---

src/l10n/at.ts

according to the german (de) locale
ref #1079

Add 'time_24hr: true' to Austrian locale

---

__tests__/src/index.spec.ts
src/index.ts

As I noted in https://github.com/flatpickr/flatpickr/issues/2653#issuecomment-1064139109, #2419 didn't handle altFormat properly and caused the issue #2653 and #2660.
This PR fixes the issue, by removing most of the fix from #2419. That's because It turned out that the fix made by #2541 and #2601 also addresses the issue #2419 was trying to solve.

Fix #2419 breaking with altInput and altFormat Enabled
