flatpickr/flatpickr

- index.html
- src/flatpickr.js
hi,
this pull-request enables flatpickr to use a custom date parser instead of the built-in method. this way it’s possible to use advanced parsers like the one moment.js provides.
> add ability to parse date using a user-defined date-string parser

- src/style/flatpickr_base.styl
fixed the missing text color in dark theme style for time separator and am-pm text
> Updated text color in dark theme style

- src/flatpickr.js
Typing something other than a digit into a time input causes parseInt to return NaN, which breaks a bunch of stuff. Once the time picker is broken, it can't be fixed without refreshing the page, even if the input field is cleared and a number is added.
This patch causes NaN results to become 0, which will prevent this problem from popping up.
> Fix issue with invalid time inputs

- src/flatpickr.js
This patch lets developers set the seconds value, which wasn't possible before without also specifying a date.
It also fixes a couple of issues surrounding this bug, both of which were caused by JavaScript treating 0 as a falsy value.
> Load seconds into intitial time value

- src/flatpickr.l10n.fr.js
Hi,
I've switched first day of week to 1 for the FR l10n since it's what's most common, in France at least.
(in the right branch this time)
> Fix first day of week for l10n.fr

- src/flatpickr.js
Fixes #383, see issue for further details.
> adjust timeRegex in parseDate to make seconds optional

- src/flatpickr.js
- test/spec.js
Custom `formatDate`-support. To provide better integration with other i18n-modules (eg. `angular-i18n`)
> support custom `formatDate`-function

- dist/flatpickr.js
- src/flatpickr.js
I've dropped most uses of innerHTML, as textContent is like 5x faster for these tiny text-only strings. The prevArrow/nextArrow are still using innerHTML, due to the inline SVGs. It'd be nice to avoid innerHTML here, but that's a larger refactor.
I've also removed the default parameters for `createElement` as the compiled version relied on `arguments` which isn't very performant in a hot path.
On my macbook air, I'm seeing the times of `build()` go **from ~9ms to ~2ms**.
For the demo page, the full startup has gone **from ~400ms to ~230ms**.
So, let's average that out and say we're **~300% faster**. 🔥 
Here's a before and after trace: https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/7238b2rphoof6j7/flatpickr-before.json?dl=0,%20https://www.dro …
> Better startup performance

- site/content/examples.pug
Currently, the example uses a max date in the past rendering the demo unusable. This change moves the max date to the future. I guess this problem will happen again in a year, but for the sake of documentation brevity, I figure this is the best solution.
> Set max in range limit example to future

- src/l10n/de.js
* monday is usually the first day of the week in german calendars
* weeks are abbreviated 'KW' for 'Kalenderwoche'
> update german translation

- src/flatpickr.js
- Changed `document` references to `window.document` so all events are
handled at the window document level, even when flatpickr is present
inside a web component with its own document element.
- Added two checks in `documentClick` that inspect the event path to see
if either the `input` or `altInput` elements have been selected when
flatpickr is run within a web componet. If it is, then the event target
will point to the web component. The path will contain the input
elements if they're a part of the event.
> Made flatpickr capable of being used within the context of a web component

- src/flatpickr.js
IE11 has classlist, but it does not support multiple arguments for add() and remove().
Since it is used in 2 places in range mode related code, the picker renders weirdly, like this:
See http://caniuse.com/#feat=classlist
> fix range mode styling in IE11

- site/content/API.pug
- site/sidebar.pug
Hey, we just noticed this param was missing from the documentation so we added it in
> added info about triggerChange to onDate

- src/flatpickr.js
New date format "Z" that formats the entire date value using toUTCString(). Useful for the config.dateFormat as it allows to POST date value converted to UTC to the web server while allowing the user to manipulate the date in local time thanks to config.altFormat.
> New format to be able to post date value in UTC

- src/flatpickr.js
When I set `enable: {from: "today"}` to 3 inputs, the first input became empty.
```html
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src='src/flatpickr.js'></script>
<link rel='stylesheet' href='dist/flatpickr.css'></script>
<input value=2017-02-23 class='pickr-input'>
<input value=2017-02-23 class='pickr-input'>
<input value=2017-02-23 class='pickr-input'>
<script>
$(function(){
var config = {
altInput: true,
enable: [
{
from: 'today',
to: new Date().fp_incr(99999)
}
]
}
$('.pickr-input').flatpickr(config)
})
</script>
```
result: 
expected:
this pull fix the order of parsing enable&disable rules and setSelectedDate.
setSelectedDate after "today"(string) has been overwritten to Date).
> set selected date after parsing rules

- src/l10n/et.js
Pretty straightforward, noticed a translation was missing when using flatpickr in one of our projects.
> Add rangeSeparator for Estonian l10n

- src/flatpickr.js
- test/flatpickr.spec.js
If we pass a configuration object with `undefined` values for the hooks the property is set and an update triggers a TypeError:
```js
new Flatpickr(element, {
onChange: undefined
});
```
I fixed it by removing all undefined values on the `instanceConfig` object. Unfortunately I couldn't use the trick `JSON.parse(JSON.stringify(obj))` because there are functions in the object. Hence I created a function to clean an object.
> Clean instance config object

- src/style/flatpickr.styl
allowInput controls the readonly attribute. When the user can manually edit the input field, it makes no sense to change the default input pointer as it remains fully functional.
Fixes #669
> fix(css): Add [readonly] condition to cursor style

- src/flatpickr.js
The timestamp `0` refers to the date `1970-01-01`, which is a valid date.
Exluding timestamps of `0` stops the `onValueUpdate` hook from firing on
init if the date is `1970-01-01`.
> Allow timestamp of 0 to be included in selectedDates

- src/flatpickr.js
Fixes a TypeError which occurred when using the scroll wheel on elements other than the hour or minute input fields (e.g. up- and down arrow)
Fixes #682
> Fixes TypeError on scroll

- src/l10n/nl.js
In Dutch, unlike in English, the names of days and months don't start with a capital letter. The only exception is when they're used as the first word in a sentence, but this doesn't apply to Flatpickr (the names of days/months are part of the UI, so not officially a sentence).
This PR corrects the capitalization for the Dutch translations and also fixes an incorrect abbreviation for the month March (should be "mrt", not "maa").
> Corrected capitalization for Dutch days and months

- src/flatpickr.js
> (fix) Retain Flatpickr metadata when copying `Date` instance

- dist/l10n/lt.js
I fixed month names in Lithuanian translation. Somehow they have some characters that do not even exist in Lithuanian.
> Fixed incorrect characters in Lithuanian translation

- package.json
- src/flatpickr.js
This checks if `window` exists before checking `window.navigator` when creating the default config.
Without this check, Flatpickr cannot even be loaded in Node.js (for e.g. server-side-rendering of the react component).
This has a side-effect of disabling animation in Node.js :P
I also added a very simple test that just runs `require('require('./src/flatpickr.js')` in Node.js. A more comprehensive test might be to build the dist folder and then require `dist/flatpickr.js`, I can switch it if you'd prefer. Note that this test must run outside of Jest, because Jest automatically pollyfills `window`, which would make it pass even when it shouldn't.
This fixes the root cause of the following issues:
* https://github.com/coderhaoxin/react-flatpickr/issues/9
* …
> Basic support for server-side-rendering

- content/options.md
Adds rows to the table on the Options page in the docs for these two (relatively recently added) options.
> Document the ariaDateFormat and formatDate options

- src/plugins/confirmDate/confirmDate.ts
This looks like a typo. Instead of passing a property called `pluginConfig`, we need to inline the user's config options into `config`.
EDIT: Sorry, I accidentally submitted without going through CONTRIBUTING.md. Reading now, will update this for compliance.
EDIT 2: I can't easily show a fiddle demonstrating the bug, as the code with the bug hasn't been released yet. I found this bug because I inlined `dist/plugins/confirmDate/confirmDate.js` into my own project to test some modifications, and realised my config options weren't having any effect.
> Fix confirmDate plugin config options

- src/__tests__/index.spec.ts
- src/utils/index.ts
Like I described in https://github.com/chmln/flatpickr/issues/734, with a specific set of conditions (Windows, Firefox and scrolling with a trackpad), delta values from the `wheel` event can be between -1 and 1, resulting in bogus increments of years or months.
> fix mouseDelta function

- src/l10n/da.ts
In Danish nouns are not written with capital letters.
The correct way to write a Danish date is i.e. "18. oktober 2017".
> Lowercase Danish nouns

- content/getting-started.md
I added [jsDelivr CDN links](https://www.jsdelivr.com/package/npm/flatpickr) to your site as an alternative to unpkg. jsDelivr is the fastest opensource CDN available and built specifically for production usage. It can serve any project from npm with zero config just like unpkg, but offers a larger network and better reliability. We also have detailed usage stats for project maintainers.
> Add jsDelivr links

- src/plugins/labelPlugin/labelPlugin.ts
Label plugin doesn't work on mobile devices. Label click (touch) doesn't open datepicker.
There is fiddle with current version and fixed one. 
[https://embed.plnkr.co/0kJLFhiv0lXuzQsdINLN/](https://embed.plnkr.co/0kJLFhiv0lXuzQsdINLN/)
> fixes labelPlugin on mobile

- content/options.md
All types changed to begin with an uppercase letter.
This change fixes issue #945
> Cleans up the type field in the docs for option

- .jest.ssr.json
- package.json
- src/__ssr_tests__/index.spec.ssr.ts
- src/index.ts
- src/types/options.ts
The switch to typescript seems to have caused a regression from the changes in #969. This adds a very simple SSR test, while also setting up a framework for adding more, which will automatically get run with the other tests.
> Add basic server-side rendering support

- index.d.ts
Useful when we need for example to do :
```ts
import { Hook } from 'flatpickr';
```
> Typing : export all options type

- src/utils/formatting.ts
- tsconfig.json
This PR will add the noImplicitAny option into tsconfig.json file (#1120).
I had to disable this option in my project because when compiling flatpickr module, tsc gave me this error:
_./node_modules/flatpickr/src/utils/formatting.ts at line 30_
Function expression, which lacks return-type annotation, implicitly has an 'any' return type.
> Add noImplicitAny option in tsconfig (#1120)

- src/utils/formatting.ts
This just defines the return type for the `do_nothing` arrow function to avoid "no implicit any" errors in dependent apps.
> fix "no implicit any" error in utils/formatting

- content/plugins.md
It has 2 fixes for plugin documentation:
- A fix for hooks URL
- The same proposed in the pull request #1164
> Correcting links: hooks and plugins.

- .npmignore
- tsconfig.json
when installing flatpickr via npm, all the ts-files in `src` do not exist. this leads to a ts-error.
fixes https://github.com/chmln/flatpickr/issues/1210
> fix: add `dist`-folder to tsconfig.json; correct typo in `lib`

- src/style/flatpickr.styl
> Fix header month/year being clipped in IE11

- src/l10n/it.ts
Correct italian range formalization would be: "Dal 05/02/2018 **al** 06/02/2018".
>  Add Italian rangeSeparator

- src/index.ts
By always preventing the default event in `onMonthNavClick` no unwanted focus events get handled which caused faltpicker to immediately close in e.g. a BS modal.
This closes #1190.
> Always `preventDefault()` event in `onMonthNavClick`

- src/index.ts
When using altInput, the new input field has no tabindex attribute, which can disrupt the order of focus of the element in a formular.
This change copies the original value to the alternative input element.
> altInput accessibility: use tabIndex from the original input element

- index.d.ts
Hi there! After 4.2.1 which adds the default module export, typescript users have to change the flatpickr import from:
```
import * as flatpickr from 'flatpickr';
```
to
```
import flatpickr from 'flatpickr';
```
However, the typings don't match up to this and the typescript compiler complains with "flatpickr has no default export", unless you set `allowSyntheticDefaultImports` in your tsconfig. This small change aligns the typings with the actual module shape and should avoid these types of errors for people so they can use it with typescript with no friction.
> fix(typings): use correct default export

- src/index.ts
In out application, we use a namespaced stylesheet. I've managed to solve for this issue by adding a namespaced class to each of the flatpickr elements in the onShow hook. Here's what happens...
this....
`
<span class="arrowUp"></span>
`
becomes...
`
<span class="arrowUp node-1234-arrowUp"></span>
`
All the styling is applied perfectly, but the up and down year selector arrows don't functions because a condition expects a specific value for the class attribute. My pull request solves for this issue. Also, my code change is more inline with other conventions in your code.
Thanks!
> onMonthNavClick use classList in condition

- src/__tests__/index.spec.ts
- src/index.ts
> 681 show disabled arrows

- src/__tests__/index.spec.ts
- src/index.ts
Problem: Initialization for mobile with enabled confirmDatePlugin cause an exception, due to plugin expect property `isMobile` that setuped after plugins initialization.
Solution: setup isMobile before initialize plugins.
> Fix init on mobile with enabled confirmDatePlugin

- src/index.ts
This PR fixes #1378.
The ternary predicate will now also return as falsy if `self.input.placeholder` is null or undefined.
This prevents the check from throwing an error if `self.input` is something other than an `input` element (e.g. buttons), as mentioned in #1378.
>  Swap placeholder length check with not-null & empty check.

- src/index.ts
**What's Changed?**
Added a check if there is no element selected in IE (document.activeElement is null) it will pass the body element to dayFocused.
**How To Test**
In Internet Explorer, use the keyboard to select dates in a month outside of the currently selected month.  Use Control + up/down/left/right cursors to change month and year
**Notes**
Chrome, Firefox and Safari will return the body element as document.activeElement if nothing is selected but Internet Explorer 11 will return null
> make sure active element is not null

- src/index.ts
If `destroy()` is called on a flatpickr instance after it closes but before the 300ms `onChange` timeout, then `triggerEvent` will throw an error when it eventually looks for `onChange` hooks, because `destroy()` removes the config. This PR fixes that problem.
> Prevent error due to onChange firing after destroy() is called

- src/index.ts
Added to the handler for tab event so if you tab off flatpickr it will refocus your input element instead of jumping to the beginning of the DOM
How To Test
1. Add some links to the page before and after your input element so you can track the focus
2. Open flatpickr with a calendar
3. Use the cursors to navigate
4. Press tab.  You'll now end up at the next element on the page instead of at the top of the page
also
1. Open flatpickr with noCalendar: true and enableTime: true
2. Set a time, press tab past the AM/PM
3. You'll now end up at the next element on the page.
Notes
Issue #1236 says the desired behaviour for time only would be that tab would loop through hour/minute/am-pm but I would prefer it close flatpickr as it currently does.
> Handle focus when tabbing out of flatpickr

- emitDeclarations.sh
The correct paths can't be found because we don't just export the language definition, but always merge it with existing ones on `window` and export the result. This is something that is likely never supported well in TypeScript. For now I think a simple addition to the `build:post` step suffices.
Fixes #1440
> Fix wrong path for types

- src/index.ts
Calling a manual flatpickr.set() to change options will now update the date shown in the input
How To Test
Use the HTML and JavaScript in this fiddle: https://jsfiddle.net/49g1r80d/
Clicking the 'Change format' button will update the input right away without having to open the date picker again.
Notes
Relates to issue https://github.com/flatpickr/flatpickr/issues/1431
> Update value on set

- src/index.ts
No functional changes. Using a different selector to get the same element.
How To Test
Test the year input on date picker and minutes/hours/seconds on time picker. 
Notes
I wasn't able to reproduce the problem but it's related to issue https://github.com/flatpickr/flatpickr/issues/1457 . Possibly something is adding unnecessary whitespace. According to stack overflow, "Some browsers include empty textNodes, some do not"
> Avoid use of child nodes for browser support

- src/index.ts
In my project, we are using flatpickr in such a way that we create "virtual" instances whose wrappers aren't actually inserted into the DOM. In the current code, this throws an error when `destroy` is called because it tries to remove children on the parent node's wrapper.
This just adds a simple check to prevent that error in case the wrapper has no parent.
Also, I noticed that with a datetime picker you can no longer change the time with the arrow keys. I restored an earlier piece of deleted code that restores this functionality.
> prevent error on destroy if wrapper has no parent node, restore keyboard control for time on datetime picker

- src/index.ts
* Added an OR to solve the issue of pressing up/down cursors when the input is still the active element (flatpickr was just opened)
* Added a e.stopPropagation() to prevent jumping 2 years the first time you press ctrl+up or 2 months the first time you press ctrl+right
How To Test
Try cursor keys with default options, try with enableTime: true and with noCalendar: true
Notes
Relates to https://github.com/flatpickr/flatpickr/pull/1461
> Fix cursor problems

- src/l10n/lv.ts
1. Make all short day name consist of 2 letters
2. Fix mixed April and May short month names
> Fix Latvian language translation

- src/index.ts
**The problem**
When I manually trigger the opening of the picker, I want it to be focused on the current date so that keyboard users can immediately navigate.
My use-case is that I have a little datepicker button that a user can click to open the datepicker on the side of my input.
**The solution**
If the active element isn't in view, focus on the current date. This might need a bit of adjustment for correctness, but I'm happy to make changes as required.
**Side benefits**
- I also trigger the opening of the calendar manually if a user presses ArrowDown whilst focused on the <input>, this input is also using `allowInput: true` in the configuration. This allows me to use keyboard navigation again. (before doing this fix, keyboard navigation didn't seem to work)
**Workaround using hooks** …
> fix: focus datepicker when self.open() is called

- src/index.ts
This is a rehash of a mysteriously disappearing PR from another developer.
Essentially the picker is always offscreen on devices such as the iPhone 5, and other small screen devices.
The original PR was: https://github.com/flatpickr/flatpickr/pull/962
I've basically lifted the code directly from that PR.
This should therefore fix:
#1389
#1040
#874
This potentially fixes:
#1024 
#1318
I'll get a codepen up or similar if I can figure out how.
> fix offscreen issue on mobile

- src/index.ts
In some edge case I saw an error in the console (I'm using flatpickr in combination with react-flatpickr).
```Uncaught TypeError: Cannot read property 'style' of undefined```
It was caused by an unmount which happened very fast after the mount. Therefore the init logic of flatpickr was not completely finished. This change should fix this.
> Fixed error when the datepicker is destroyed before it is initialized

- emitDeclarations.sh
The script is marked as posix shell script, is started using a posix shell
script but uses bashisms. The script will therefore fail with a posix
shell:
$ sh ./emitDeclarations.sh
./emitDeclarations.sh: 4: ./emitDeclarations.sh: [[: not found
error Command failed with exit code 127.
But this bashism can easily be replaced with POSIX only code that also
works with bash.
> Remove bashisms from emitDeclarations.sh

- src/index.ts
The flatpickr generates following error on XHTML pages when the weekdays are generated:
DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
at updateWeekdays (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:1114:59)
at buildWeekdays (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:1101:11)
at build (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:781:43)
at init (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:493:15)
at FlatpickrInstance (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:2197:7)
at _flatpickr (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:2212:33)
at flatpickr (https://example.com/ext/flatpickr-4.5.1/flatpickr.js:2234:14)
at …
> Fix XHTML compatibility of weekday list

- src/__tests__/index.spec.ts
- src/index.ts
- src/types/instance.ts
Currently the function constructor only allows a `NodeList` or `HTMLElement`, which is conceptually accurate & successfully captures the majority of usecases. However, there are issues with choosing this implementation:
1) `NodeList` is too restrictive an interface. While it's effectively the same as `NodeListOf<HTMLElement>`, it's definitively *not* the same as `HTMLCollection`, a separately supported interface. Both would be adequately supported by leveraging the built-in `ArrayLike<T>` interface.
2) `HTMLElement` is also, paradoxically, too restrictive an interface. Internally it's necessary to guarantee the object is an `HTMLElement` so we can access `node.getAttribute` inside the `_flatpickr` loop. The trick is, while the outer type "protects" us from this foul, no actual check …
> Loosen type requirements & fix empty set handling

- src/__tests__/index.spec.ts
- src/index.ts
- src/types/instance.ts
> Reset currentMonth and currentYear when clear() is called

- emitDeclarations.sh
The copy-command used for macOS (Darwin) in emitDeclarations.sh was missing a slash at the end, causing the resulting file-structure to be incorrect.
Fixes #1665
> build(emitDeclarations.sh): correct copy command for macOS

- src/index.ts
Removed Array.from method so it'll work in IE (#1662)
How To Test
Try it in IE
Notes
We could do this with a polyfill, but it's a pretty big one, so I would suggest this work around
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill
> remove Array.from

- package.json
- src/index.ts
Fixed issue #1661 when tabbing off flatpickr using altInput
How To Test
1. Add a focusable element before and after the flatpickr input.
2. Tab to the input, tab off again. It should go to the next element, not back to the top
Notes
Tested with 
{
enableTime: true,
altFormat: "H:i",
altInput: true,
noCalendar: true,
dateFormat: "H:i",
}
and
{
enableTime: true,
dateFormat: "Y-m-d H:i",
altInput: true,
altFormat: "m/d/Y",
}
> check for altInput on tab off

- src/plugins/confirmDate/confirmDate.ts
This happened because the plugin is instantiated only one time, meaning that the `confirmContainer` variable was instantiated once and then overwritten every time `onReady` was called (twice in the example from #1386). 
In the `onChange` listener, the confirm container should be accessed through the fp instance, not through the global variable from above
> Fix #1386 - confirm panel visibility for multiple flatpickr instances

- src/__tests__/index.spec.ts
- src/index.ts
- src/style/flatpickr.styl
PR redid
Original text: The `disabled` CSS class had a too common name and introduced subtle bugs like the one in #1572 . Renamed the class to `flatpickr-disabled`. The purpose was to save time both for the users and the maintainers in the future when investigating these kind of bugs
> #1572 - renamed CSS class disabled to flatpickr-disabled

- src/index.ts
- src/plugins/confirmDate/confirmDate.ts
- src/plugins/labelPlugin/labelPlugin.ts
- src/plugins/minMaxTimePlugin.ts
- src/plugins/monthSelect/index.ts
- src/plugins/rangePlugin.ts
- src/plugins/scrollPlugin.ts
- src/plugins/weekSelect/weekSelect.ts
- src/types/instance.ts
I was looking for a clean way to check that the monthSelect plugin has been loaded inside the confirmDate plugin (to enable the confirm button if the monthSelect is loaded) and there wasn't any. I added an attribute called loadedPlugins on the fp instance in which each plugin pushes its own name.
Same problem was referenced in #1217
> Added loadedPlugins attribute on fp instance

- src/plugins/monthSelect/index.ts
- src/plugins/monthSelect/style.css
Realized that the dark theme parameter for the month select plugin required the dark theme in the main picker to look ok. I made it work without it also
> Monthselect plugin dark theme parameter now works standalone

- config/rollup.ts
- emitDeclarations.sh
- package.json
I am looking at doing some development and bug fixing.
These changes help me and hopefully others debug and build in vscode which is very popular and cross platform.
The changes are not code editor specific so I think they are a good addition.
1.  Emitting a sourcemap lets me attach a chrome debugger and set breakpoints in typescript using vscode..
2.  Making the build scripts more cross platform means build system is more accessible.
I changed fd for find as fd is not always available by default.
Tested on windows 7  with git bash and mac.
> Build system improvements

- build.ts
- config/rollup.ts
Finally I managed to sourcemap all the things.
This means when we do `npm start` we can set breakpoints in typescript code.
This includes locales and plugins so debugging will be much easier.
I will add the launch config for vscode in another PR but it makes debugging so easy for new devs.
Hopefully with this and some docs for editors we can get more people fixing bugs.
Took me quite a few hours to workout what was happening with rollupConfig but I'm pretty confident its all ok.
For release build just
`npm run build`
which will delete dist and recompile with out sourcemaps as before.
> Source maps for --dev

- emitDeclarations.sh
- package.json
Remove unnecessary mkdir. this is already done in build.ts
https://github.com/flatpickr/flatpickr/blob/0e1014b156ca8db18501ed7f33608ab192efa9d5/build.ts#L253
Remove unnecessary find command as relative paths are already correct after compile.
The upshot of this is `npm run build` now works on cmd and powershell on windows which are common shells.
> Allow rebuild on powershell and cmd.

- .eslintrc.js
Since this repo uses some modern ecma language features 
```
"lib": [
"es2015",
"dom",
"es2017.object",
"esnext.asynciterable"
],
```
Note this is only for parsing and linting and does not  upgrade language features that are not already present.
Babel deals with the browser compatibility anyway.
> Support ecma 2018 parsing

- package.json
- src/__tests__/index.spec.ts
- src/tsconfig.json
Was failing strict null checking seems to get past roll-up
EDIT see below for commit that solves type checking and will prevent this in the future
Setting focus not required for test.
> Fix test - fails strict null checking

- .eslintrc.js
- build.ts
- src/index.ts
- src/types/instance.ts
- src/utils/dates.ts
- src/utils/formatting.ts
time_24hr is a pain point
My take is to change the Locale types to time24hr as that removes a lot of violations and exempt the rest.
Ultimately I think a config option time24hr would be more consistent with the rest of the options but that would break a lot of people.
I think the Locale types are internal only so it just means anyone that creates a new locale can use time24hr but I don't see that being a problem.
I have taken care to keep the Interfaces and config parsing the same.
I noticed which is bad performance wise
https://github.com/flatpickr/flatpickr/blob/eff1511a4581a969341d2f510ad13184e820a3ec/src/index.ts#L2876
#1498
> Fix @typescript-eslint/camelcase

- .eslintrc.js
- build.ts
- config/rollup.ts
- src/__tests__/index.spec.ts
- src/index.ts
- src/plugins/monthSelect/index.ts
- src/plugins/monthSelect/tests.spec.ts
- Please check `lastDate` variable that I removed.  I checked and I couldn't see any point looping past `rangeEndRange` but I could be wrong.  Could also be a minor performance improvement for multi month range
- I noticed there is a few examples in the code that use type assertions to circumvent the null issues when collecting config from dom attributes.
- In this PR I did use it myself for the attributes of the time inputs which will result in a NaN if the attribute is missing which is not a bad solution but we could go to `self.config` directly for min max step etc which will always be more up to date than the dom.
- Since rollup has an optional output config I just excepted that .
- Most of the changes are in tests.
> Fix @typescript-eslint/no-non-null-assertion

- src/index.ts
Fixes #1764
Flatpickr doesn't open on mobile chrome version 73+
Replaced click event that was used to handle touch with touchstart to support mobile browsers
> Calendar does not open on Android Chrome

- src/plugins/monthSelect/index.ts
I was using a forEach in the month plugin to iterate through a NodeList, which apparently is not supported by IE. I've replaced all forEach calls with a normal for loop.
> #1344 Removed forEach on NodeList - not working in IE

- src/l10n/ar.ts
- src/l10n/id.ts
- src/l10n/ja.ts
- src/l10n/ko.ts
- src/l10n/vn.ts
- src/tsconfig.json
When I added the language separators last week, I forgot to run ts-node locally and the files were not auto formatted. Now, every time I try to do anything, it formats the files from then and adds them to my git changeset. This fixes the problem by merging the already formatted files to master
> Fixing unformatted files

- src/l10n/ja.ts
Thanks for great library!
First day of a week is Monday in Japan. 😃
> Setting Monday as firstDayOfWeek for Japanese

- src/index.ts
Fixes #1856, I forgot to use the shorthand when creating the month name in the dropdown
> Fixed shorthandCurrentMonth not working for month dropdown

- src/style/_vars.styl
- src/style/flatpickr.styl
Based on #1854 - now letting the browser device the height of the month select, so it doesn't cut text anymore
> Improvements for month select

- src/index.ts
- src/types/options.ts
Implementes #1826
Flatpickr still defaults to the dropdown, but setting the option to `static` reverts to text representation
> #1826 Added monthSelectorType option

- src/index.ts
Fixes #1887, or at least part of it.
The logic for pressing up/down arrow keys when the input is active didn't take the altInput element into account.
> Allow keyboard navigation when using altInput

- src/index.ts
When using flatpickr in time-only mode and refresh the locale the `updateWeekdays` gets triggered and dies in a
```
TypeError: Cannot read property 'children' of undefined
at updateWeekdays (flatpickr.js:1345)
```
> Only update weekdayContainer when initialized

- src/index.ts
- src/plugins/confirmDate/confirmDate.ts
- src/plugins/monthSelect/index.ts
- src/plugins/scrollPlugin.ts
- src/plugins/weekSelect/weekSelect.ts
Related https://github.com/flatpickr/flatpickr/pull/1568/
**Problem:**
While developing a webcomponent wrapper I faced many issues like keyboard events wasn't working. Root cause was  event retargeting in shadow dom. i.e. "events that happen in shadow DOM have the host element as the target".
**Solution:**
replace `event.target` with `getEventTarget(event)` everywhere. 
Thanks @jgroth for developing this awesome method.
> Fix event target issue in shadow dom

- src/__tests__/index.spec.ts
- src/index.ts
This PR makes sure to only apply the `step` attribute to the mobile input when it's present on the main input. Setting it always and use `any` as fallback values can cause issues on some mobile devices.
Closes #1982.
> fix: only apply `step` attribute to mobile input when present on main input (closes #1982)

- package-lock.json
- package.json
- src/__tests__/index.spec.ts
- src/index.ts
These are a couple of minor fixes to fix issues #1881, #1882, and #1961 around months being updated when changing years and changing config options programatically. I also fixed the unit tests to run correctly independent of what time zone the computer running the tests is in.
> Issues #1881, #1882, #1961

- src/index.ts
- src/l10n/default.ts
- src/types/locale.ts
We are getting errors from the [WebAIM WAVE browser extensions](https://wave.webaim.org/extension/) for a missing label on the months select. Adding an `aria-label` fixes the issue.
> Add aria-label to months

- src/index.ts
I have a use case where I don't want to use the flatpickr input, only the calendar. The recommended way of doing so is by using the `wrap` config with a hidden input.
Everything is working fine other than not being able to move the cursor with the arrow keys (left and right). I identified that the `onKeyDown` listener is preventing the default behavior while the calendar is open.
You can check it out in [this sandbox](https://codesandbox.io/s/determined-rain-k6btd). Just type whatever in the inputs or select a date (focus the input again to open the calendar as the bug only happens while it is open), and try to move the cursor left and right.
The change in this PR fixes it.
Thanks for your work on this library! Let me know if I missed anything.
> Fix onKeyDown evt listener not working with the `wrap`config

- src/__tests__/index.spec.ts
- src/utils/dates.ts
- src/utils/formatting.ts
- src/utils/index.ts
Hey,
The native datepickers when used with a keyboard were failing for intermediate values, like entering only the first character for a year.
These are the fixes.
> Fix mobile datepickers when used with a keyboard

- README.md
I created a Lit Element wrapper for Flatpickr, and am planning to optimize it as time goes by.
Added it to the see also part with other implementations
> Add Lit Flatpickr to the "See also" -section

- src/utils/dom.ts
- in some cases (might depend on Framework used, in our case it's SalesForce), it can throw an `illegal invocation` error and if that is the case then catching the error and defaulting to `return event.target` is what works. This PR wraps the code in a try/catch and if an error is caught then will default to `return event.target`
- fixes #2157
> fix #2157 - Dom Util getEventTarget sometime throws illegal invocation

- src/plugins/monthSelect/index.ts
Noticed some bugs while using the plugin:
- The left arrow only works when February is selected; the right arrow doesn't work
- With dates less than a year in the past disabled, using the left arrow selects a month outside the allowed range
This PR fixes the above issues, but arrow navigation is still broken in that you have to have January/December selected in order to move to the previous/next year.
> monthSelect plugin fixes

- src/index.ts
- src/style/flatpickr.styl
Extends `position` option to justify right. Includes fixes for moving the arrow as well.
Extends and fixes issue #1849 
Will update documentation as well
> Support right alignment with arrow styles - fixes #1849

- package.json
https://chmln.github.io/flatpickr redirects to https://flatpickr.js.org so it should be used as homepage url to prevent unnecessary redirect.
> update homepage url in package.json

- src/index.ts
We needed the support a case where neither positioning the datepicker above or below the input works.
With this you can send in a function in the `position` option and do the positioning that way.
This is what our positioning function looks like (in an ember component):
```js
import { createPopper } from '@popperjs/core';
// the rest of the component here :)
handlePosition(flatPickrInstance) {
if (!this.popperInstance) {
const arrowElement = document.createElement('div');
arrowElement.classList.add('datetime-picker__arrow');
flatPickrInstance.calendarContainer.appendChild(arrowElement);
this.popperInstance = createPopper(
flatPickrInstance.element,
flatPickrInstance.calendarContainer,
{
placement: 'bottom',
strategy: 'fixed',
modifiers: [
{
name: 'arrow',
options: {
element: arrowElement, …
```
> support function for `position` option

- __tests__/src/plugins/monthSelect/index.spec.ts
- src/plugins/monthSelect/index.ts
Fixes #2277.
Originally, in the monthSelect plugin,
clicking on the prev/next year buttons
failed to update the year shown at the top of the calendar
until after the user made an initial selection.
Under the hood, clicking the prev/next year buttons did change the year,
meaning that the selected month/year would not necessarily match
the month/year displayed in the UI.
This occurred because the line that updates the view
was hidden behind an `if` clause that it shouldn't have been.
This commit moves that line to the appropriate place.
> Fix stale year display in monthSelect plugin

- __tests__/src/plugins/monthSelect/index.spec.ts
- src/plugins/monthSelect/index.ts
Fixes #2279.
This commit fixes a multi-layered bug
in which the prev/next year buttons in monthSelect
do not honor the `minDate` / `maxDate` config options.
That is, the months (cells) outside of the given bounds are disabled,
but the user is free to navigate to any year (page)
regardless of minDate/maxDate settings.
There were two problems at play:
1. First, the listeners on the prev/next year buttons had to be fixed.
Originally, they blindly incremented/decremented the given year;
now, they reuse an existing `changeYear()` function,
which performs this check (among other things).
- fp.currentYear--;
+ fp.changeYear(fp.currentYear - 1);
2. That mostly fixed the problem, but left one small wrinkle:
the prev. year button was still visible on the screen
when reaching the minYear bound. …
> Fix monthSelect plugin's minDate/maxDate handling

- src/l10n/ja.ts
- src/types/locale.ts
monthAriaLabel added default l10n but, didn't add custom l10n. so add attributes and Japanese translation.
reference https://github.com/flatpickr/flatpickr/pull/2082
> add monthAriaLabel

- __tests__/src/index.spec.ts
- src/index.ts
I am proposing a reversion of the merge #2127, which addressed issue #2126. This commit made flatpickr use 'click' events instead of 'mousedown' events in order to be compatible with [WCAG 2.1](https://www.w3.org/TR/WCAG21), specifically [2.5.2 Pointer Cancellation](https://www.w3.org/TR/WCAG21/#pointer-cancellation).
This change has introduced some strange behaviour in flatpickr because of the way that 'click' works. The fact that flatpickr runs identical events for both focus and click events ensures that compatibility with WCAG 2.1 - 2.5.2 is not possible. Think of the following scenario:
**A user 'clicks' into a flatpickr input field:**
- The browser fires a Focus event - flatpickr runs self.open (therefore invalidating WCAG 2.1 compatibility as there is no way of cancelling this …
> Fix for picker showing and hiding again

- src/l10n/ja.ts
Revert "Merge pull request #1846 from lightsound/update-ja"
I think that the first day of the week in japan is Sunday instead of Monday.
There are two reasons.
The first one is that the Kojien (Japanese Dictionary) says that Sunday is
first day of the week.
The second one is that Labor Standards Act in Japan says the default
week is Sunday to Saturday. [昭63.1.1 基発1号](https://www.mhlw.go.jp/web/t_doc?dataId=00tb1899&dataType=1&pageNo=1)
Because of these two reasons, The first day of the week is Sunday.
Also most  the first day of the week of [Japanese Calendar(Google Search)](https://www.google.com/search?q=%E6%97%A5%E6%9C%AC%E3%80%80%E3%82%AB%E3%83%AC%E3%83%B3%E3%83%80%E3%83%BC&tbm=isch&ved=2ahUKEwjD8a27o53tAhUKzJQKHTjVAw8Q2-cCegQIABAA&oq=%E6%97%A5%E6%9C%AC%E3%80%80%E3%82%AB%E3%83%AC%E3%83 …
> The first day of the week in japan is Sunday instead of Monday.

- src/utils/dates.ts
Allow use of custom date parsers when date string's end in 'Z' or 'GMT'
Fix for issue:
https://github.com/flatpickr/flatpickr/issues/2368#issue-775640511
> Support Z & GMT custom parsing

- src/types/options.ts
Include strings for horizontal positioning in the `BaseOptions` interface `position` property.
> Add missing horizontal position strings to position option type

- __tests__/src/index.spec.ts
- src/index.ts
This feature is handy for creating maintenance windows or disabling time ranges.
For example minTime: 5:30, maxTime: 3:30 means that you can pick time from 5:30 to 3:30, which disables 3:30 to 5:30 range to be picked.
Fixes issue: https://github.com/flatpickr/flatpickr/issues/2260
> Support reversed ranges for minTime and maxTime

- package-lock.json
package-lock.json was migrated to `"lockfileVersion": 2` by an old buggy version of npm@7, and is therefore missing important information such as the `"bin"` records that npm@7 needs for new installs.
```console
$ npm i; npm run build
[…]
> flatpickr@4.6.9 build
> run-s build:pre build:build build:esm build:types build:post
sh: line 1: run-s: command not found
```
Fix it by un-migrating with npm@6 and re-migrating with a current npm@7.
https://github.com/npm/cli/issues/2147#issuecomment-731433520
> Fix incorrectly migrated package-lock.json

- __tests__/src/index.spec.ts
- src/index.ts
Related issue: #2312
The fp instance appers based on `self._positionElement`.
When executing `fp.set()`, positionElement value is set to `self.config.positionElement` but no set to `self._positionElement`.
Setting `self.config.positionElement` to `self._positionElement` is executed in `setupInputs()` method.
so add `updatePositionElement()` function and call that in `setupInputs()` and `CALLBACKS`
> [fix] apply positionElement to instance._positionElement when fp.set

- __tests__/src/index.spec.ts
- src/index.ts
- src/plugins/minMaxTimePlugin.ts
- src/utils/dates.ts
With setting maxBound 3:30 (am) and minBound 5:30 (am) the previous implementation would set time as 5:30 (am) for 3:20 (am), which is incorrect.
> Fix maxTime bound bug

- src/utils/dates.ts
Suppose the day is given as “0”. `date.setDate(0)` will set the day to the last of the previous month. With `ops.forEach` being inside the for loop this is done for every run through the loop, so for every loop we go one month back instead of only once.
For example `parseDate("0.", "d.m.Y")` gives 31.08.2020 instead of 31.12.2020.
> Fix parseDate on relative inputs

- src/index.ts
Eliminate a memory leak caused by the accumulation of capturing event listeners created by Flatpickr as `FlatpickrInstance`s are created and destroyed (reported in #2595).
1. Checkout the destination branch.
2. `npm install`
3. `npm start`
4. Navigate to http://127.0.0.1:8000
5. Open dev tools to the JavaScript console.
6. Log the `document` listeners: `console.table(getEventListeners(window.document))`
7. Destroy the `FlatpickrInstance`: `fp.destroy()`
8. Log the `document` listeners: `console.table(getEventListeners(window.document))`
9. Observe that the `focus` listener is still present.
1. Checkout the source branch.
2. `npm install`
3. `npm start`
4. Navigate to http://127.0.0.1:8000
5. Open dev tools to the JavaScript console.
6. Log the `document` listeners: …
> Eliminate memory leak caused by event listener accumulation

- src/index.ts
When you initialize the flatpickr inside a shadow dom, the the usage via keyboard doesn't work.
The activeElement from the document is the component with the shadow dom. So the condition which checks if the activeElement is inside the flatpickr instance, doesn't match.
I fixed this by get the rootNode from the calendarContainer, in normal case, it is the document. In a WebComponent, it is the Shadow DOM.
> Keyboard doesn't work inside Shadow Dom

- src/index.ts
#2499 
Already triggering 'onChange' emitter in updateTime method. 
- `updateTime`:
```
if (self._input.value !== prevValue) {
self._debouncedChange();
}
```
- `bindEvents` :
```
if (self.amPM !== undefined) {
bind(self.amPM, "click", (e) => {
updateTime(e);
triggerChange();
});
}
```
> Remove repeating 'onChange' trigger

- src/index.ts
Fix for #2054 
**The issue**
When using the appendTo option, the append to container and any children are classed as "Calendar elements". This prevents the calendar from closing when clicking outside of the calendar instance if the click target is a child of the appendTo element. 
**Fix**
Don't class the appendTo node/element as calendar elements, just the calendar instance, and its child nodes.
> Append to container and children no longer classed as calendar elements

- src/index.ts
On Safari (I'm using 14.0.2 but it occurs in other versions as well)
When the calendar doesn't fit into the screen and has to be repositioned
And the first imported stylesheet on the page is from another domain (explained below)
The function `positionCalendar` throws an error on `doc.cssRules.length`
After some research and [this post](https://medium.com/better-programming/how-to-fix-the-failed-to-read-the-cssrules-property-from-cssstylesheet-error-431d84e4a139) I found out that the `cssRules` list cannot be accessed when the imported stylesheet is from another domain. I stumbled on this because my first stylesheet import was a Google font.
On Safari, unlike other browsers, the cssRules node comes as `null` and gives a "false positive" on `getDocumentStyleSheet` method.
My approach was to …
> Fix for calendar position on Safari

- .github/workflows/main.yml
- README.md
- the GitHub Actions badge must match the "name" (from workflow) for it to pull the status
This is show the correct status badge after Flatpickr switch to GitHub Actions around Christmas and if you prefer a different name in the badge, like "CI Status" or anything else let me know.
> chore: replace CircleCI status badge with GitHub Actions status

- src/plugins/confirmDate/confirmDate.ts
Currently `confirmDate` button can only be accessed via keyboard when `Tab` is pressed on AM/PM button.
This fixes it by allowing navigating to `confirmDate` button when `time_24hr: true` as well as when seconds are enabled/disabled.
> Fixes confirmDate focus accessibility

- src/style/flatpickr.styl
Fixes #2602 
This PR proposes a fix by adding `user-select: none` to the previous/next month buttons to prevent text from inadvertently being selected.
> Prevent text selection on prev/next month buttons

- __tests__/src/index.spec.ts
- src/index.ts
- src/utils/formatting.ts
Hello 👋 
I'm a maintainer of [RailsAdmin](https://github.com/railsadminteam/rails_admin) project and currently [working on](https://github.com/railsadminteam/rails_admin/pull/3455) integrating flatpickr into that. Thank you for the hard work of publishing and maintaining this great project!
During the integration, I found some issues related to handling of localized date/time values. Please refer to the commits for details.
If there's anything I can do to get this merged please let me know, thanks!
> Fix issues with parsing localized date/time

- __tests__/src/index.spec.ts
- src/index.ts
In the current master `allowInput: true` with `altInput: true` behaves terribly, it modifies the date value every time focusing and unfocusing on the flatpickr input element.
Refs. #2541
> Fix #2541 breaking with altInput enabled

- __tests__/src/index.spec.ts
- src/index.ts
Primarily it fixes #2394 
**The cause of the issue**
When manual input is allowed, the user input was not respected, when a user clicks anywhere in the document body instead of pressing TAB key. This results in 'click'->'blur' event sequence as opposed to only a blur event. This results in setting the date always from the calendar element.
**The fix**
The fix compares the date from the input with the latest selected date; if it matches then the changes is coming from the calendar control and updates the date time from calendar control, as before. Otherwise the change is coming from the input control, and it simply overwrites the latest selected date. The synchronization step later takes care of the rest, as before.
Additionally, it contains changes to close the calendar popup when ENTER …
> fix: handling document click after manual update 

- src/index.ts
Fixes #2649
When `allowInput` is true and `allowInvalidPreload` is true and user enters some invalid value into input, Flatpickr throws an error and calendar UI is broken, because of that error. This happens because there is invalid value in self.selectedDates (set by setSelectedDate() function), but code that is executed further in setDate() function assumes that all values in self.selectedDates are always valid Date objects. 
This fix adds two simple checks to make sure we are dealing with Date objects before using Date methods.
The error can be reproduced here: https://jsfiddle.net/yd07z3vo/1/
> Bug fix: error thrown and calendar UI broken by invalid input value when allowInput is true and allowInvalidPreload is true

- src/plugins/monthSelect/index.ts
stubCurrentMonth() simply defaulted the month to 0, instead of setting it to the actual selected month.
I've also updated the index.template.html, to demo this problem
> fixes #2669 monthSelectPlugin doesnt highlight correct month, when data is loaded

- src/style/flatpickr.styl
Fixes #2757
I've removed the -webkit-box-sizing prefix and changed the order of the appearance and flex wrap
> (chore): change vendor prefix order for standard behavior
